### ISSUE TITLE
Way of including phpunit causes warning at packagist

### ISSUE THREAD

**Issue by ndeblauw** [beyondcode/skeleton-laravel#1]
When trying to submit my package (built on top of this boilerplate) to packagist, I received the error below (see also image at the bottom)
```
Deprecation warning: require-dev.../../../vendor/phpunit/phpunit is invalid, it should have a vendor name, 
a forward slash, and a package name. The vendor and package name can be words separated by -, . or _. 
The complete name should match "^[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9](([_.]?|-{0,2})[a-z0-9]+)*$". 
Make sure you fix this as Composer 2.0 will error.
```

Fixing takes as few as 
![image](https://user-images.githubusercontent.com/4344869/124315731-ae2ff580-db74-11eb-8517-1997c8d2e9db.png)

I'm not going to do a PR, as I can understand somehow as well why you did the "local include". But maybe it's better to require it the "full and correct" way. Up to you to decide!

The error in full:
![image](https://user-images.githubusercontent.com/4344869/124315326-129e8500-db74-11eb-942b-704eb96ec1eb.png)

**Comment by mechelon** [comment]
I'm not sure how this ended up in your package 🤔 I just did a test-install and PHPUnit is listed as dependency as
`phpunit/phpunit`, just like it should be.

**Comment by ndeblauw** [comment]
Also a mystery to me, actually, now. I lacked the git(hub) skills in summer to notice back then that you did include it indeed in the correct way - so I'm sorry for this issue. I'm planning on packaging some stuff up again in 2022, so I'll test this skeleton again then and let you know if I notice something.
